"""extend patient profile

Revision ID: 07da510569fc
Revises: 5b86c1af2756
Create Date: 2026-01-08 22:09:02.017722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07da510569fc'
down_revision = '5b86c1af2756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_group', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medications', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.drop_column('medications')
        batch_op.drop_column('conditions')
        batch_op.drop_column('allergies')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('blood_group')

    # ### end Alembic commands ###
