"""availability structure

Revision ID: 1d8d07ed4aed
Revises: b67e787ff17c
Create Date: 2026-01-08 20:55:51.900058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8d07ed4aed'
down_revision = 'b67e787ff17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_booked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_column('is_booked')

    # ### end Alembic commands ###
