"""Extend doctor profile with additional fields

Revision ID: 3b471d76854c
Revises: 751e8a49d8ed
Create Date: 2026-01-11 15:47:29.361198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b471d76854c'
down_revision = '751e8a49d8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_specialization', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('medical_licence_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('medical_degree', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('medical_school', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('graduation_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('board_certifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('licence_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('clinic_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('clinic_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('clinic_city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('clinic_state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('clinic_country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('areas_of_expertise', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('awards_recognitions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('research_publications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('professional_memberships', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profile', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('professional_memberships')
        batch_op.drop_column('research_publications')
        batch_op.drop_column('awards_recognitions')
        batch_op.drop_column('areas_of_expertise')
        batch_op.drop_column('clinic_country')
        batch_op.drop_column('clinic_state')
        batch_op.drop_column('clinic_city')
        batch_op.drop_column('clinic_address')
        batch_op.drop_column('clinic_name')
        batch_op.drop_column('licence_file')
        batch_op.drop_column('board_certifications')
        batch_op.drop_column('graduation_year')
        batch_op.drop_column('medical_school')
        batch_op.drop_column('medical_degree')
        batch_op.drop_column('medical_licence_no')
        batch_op.drop_column('gender')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('phone')
        batch_op.drop_column('secondary_specialization')

    # ### end Alembic commands ###
