"""Add father_history and mother_history to PatientProfile

Revision ID: 751e8a49d8ed
Revises: db1ab29ecf18
Create Date: 2026-01-08 23:18:31.475986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751e8a49d8ed'
down_revision = 'db1ab29ecf18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mother_history', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.drop_column('mother_history')
        batch_op.drop_column('father_history')

    # ### end Alembic commands ###
