"""Add additional fields to PatientProfile

Revision ID: 84d5e8333472
Revises: 07da510569fc
Create Date: 2026-01-08 22:31:53.485666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d5e8333472'
down_revision = '07da510569fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('previous_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('surgeries', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('family_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('immunizations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('insurance_provider', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('policy_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('group_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('coverage_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.drop_column('coverage_type')
        batch_op.drop_column('group_number')
        batch_op.drop_column('policy_number')
        batch_op.drop_column('insurance_provider')
        batch_op.drop_column('immunizations')
        batch_op.drop_column('family_history')
        batch_op.drop_column('surgeries')
        batch_op.drop_column('previous_conditions')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
