"""availability structure

Revision ID: b67e787ff17c
Revises: e24ca072af28
Create Date: 2026-01-08 17:04:15.254902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b67e787ff17c'
down_revision = 'e24ca072af28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('day', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('label', sa.String(length=50), nullable=True))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('label')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('day')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
