"""Add clinic_zip_code to DoctorProfile

Revision ID: c791e88fcfa4
Revises: 3b471d76854c
Create Date: 2026-01-11 16:12:18.407409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c791e88fcfa4'
down_revision = '3b471d76854c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_zip_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profile', schema=None) as batch_op:
        batch_op.drop_column('clinic_zip_code')

    # ### end Alembic commands ###
