"""Add updated_at to PatientProfile

Revision ID: db1ab29ecf18
Revises: 84d5e8333472
Create Date: 2026-01-08 22:51:47.738668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1ab29ecf18'
down_revision = '84d5e8333472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
