"""Add consultation_type to Appointment

Revision ID: e24ca072af28
Revises: 2461bdd686b1
Create Date: 2026-01-08 16:53:09.746430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24ca072af28'
down_revision = '2461bdd686b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultation_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('consultation_type')

    # ### end Alembic commands ###
